# MAIN base
baseURL = "https://ecogains.github.io/"
languageCode = "sr-Latn"
title = "EcoGains"
theme = "apsho"

# Navigation Bar
[[menu.main]]
    name = "Početna"
    url = "#home"
    weight = 1
[[menu.main]]
    name = "O nama"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Najčešća pitanja"
    url = "#faq"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Početna"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Blog"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Privatnost i uslovi korišćenja"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Kontakt"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address = "Banja Luka, BiH"
email = "ecogains.ba@gmail.com"
phone = "+ (387)"

# Footer Social
[params.social]
facebook = ""
twitter = ""
github = "https://github.com/ecogains/test"

[params]

# Header
logo = "images/logo.png"
googleAnalytics = ""

# Footer
footerTitle = "Prijavite se na našu mailing listu"
copyright1 = "Sva prava zadržana"
copyright2 = "Copyright ©  <a href=\"https://github.com/ecogains\" target=\"_blank\">EcoGains </a> {year}"

#contact
email = "ecogains.ba@gmail.com"
